POST http://localhost:3001/api/posts/ HTTP/1.1
content-type: application/json

{
    "content": "This is my **markdown** content test",
    "community": "bellingham",
    "tags": [
        "question"
    ]
}